<a href="https://colab.research.google.com/github/raghul-2005-tech/DeepLearning/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np
cancer=pd.read_csv("/content/drive/MyDrive/NPTEL-Deep learning/week-2/ovariantotal.csv")
cancer.head()


,AFP,AG,Age,ALB,ALP,ALT,AST,BASO#,BASO%,BUN,...,PCT,PDW,PHOS,PLT,RBC,RDW,TBIL,TP,UA,TYPE
0,3.58,19.36,47,45.4,56,11,24,0.01,0.30,5.35,...,0.09,13.4,1.46,74,2.64,13.7,5.5,73.9,396.4,0
1,34.24,23.98,61,39.9,95,9,13,0.02,0.30,3.21,...,0.30,11.2,1.09,304,4.89,12.7,6.8,72.0,119.2,0
2,1.50,18.40,39,45.4,77,9,18,0.03,0.60,3.80,...,0.13,15.2,0.97,112,4.62,12.0,14.8,77.9,209.2,0
3,2.75,16.60,45,39.2,26,16,17,0.05,0.74,5.27,...,0.25,17.4,1.25,339,4.01,14.6,10.9,66.1,215.6,0
4,2.36,19.97,45,35.0,47,21,27,0.01,0.10,4.89,...,0.28,11.9,0.94,272,4.40,13.4,5.3,66.5,206.0,0


In [18]:
cancer.shape

(349, 50)

In [19]:
X=cancer.drop('TYPE',axis=1)
y=cancer['TYPE']
#if axis=0 means delete the rows that contains TYPE , axis=1 means columns

In [ ]:
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
344    1
345    1
346    1
347    1
348    1
Name: TYPE, Length: 349, dtype: int64


In [20]:
from sklearn import preprocessing
min_max_scaler=preprocessing.MinMaxScaler()
x_scale=min_max_scaler.fit_transform(X)
print(x_scale)

[[2.45578349e-03 4.85071876e-01 4.70588235e-01 ... 8.37988827e-02
  7.60667904e-01 5.60447761e-01]
 [2.78074070e-02 6.55363067e-01 6.76470588e-01 ... 1.20111732e-01
  7.25417440e-01 4.32835821e-02]
 [7.35908185e-04 4.49686694e-01 3.52941176e-01 ... 3.43575419e-01
  8.34879406e-01 2.11194030e-01]
 ...
 [1.83563615e-03 4.80280133e-01 6.47058824e-01 ... 3.15642458e-01
  6.58627087e-01 2.11753731e-01]
 [1.01704165e-03 7.74788058e-01 2.20588235e-01 ... 2.45810056e-01
  7.99628942e-01 3.53917910e-01]
 [8.26863129e-04 2.50645042e-01 3.52941176e-01 ... 1.62011173e-01
  6.62337662e-01 1.65858209e-01]]


In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scale,y,test_size=0.3,random_state=0)

In [ ]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(32,activation='relu',input_dim=49))
model.add(Dense(32,activation='relu'))
model.add(Dense(1,activation='sigmoid'))


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,batch_size=32,epochs=15)

Epoch 1/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5164 - loss: 0.7436
Epoch 2/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5164 - loss: 0.6959 
Epoch 3/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5738 - loss: 0.6785 
Epoch 4/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6230 - loss: 0.6657 
Epoch 5/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6680 - loss: 0.6522 
Epoch 6/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6967 - loss: 0.6407 
Epoch 7/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7049 - loss: 0.6264 
Epoch 8/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7336 - loss: 0.6106 
Epoch 9/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7746 - loss: 0.5915 
Epoch 10/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7869 - loss: 0.5719  
Epoch 11/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7787 - loss: 0.5503 
Epoch 12/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7910 - loss: 0.5273 
E

In [ ]:
y_pred=model.predict(x_test)
y_pred

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


array([[0.70191944],
       [0.38713196],
       [0.6351708 ],
       [0.20691009],
       [0.6924971 ],
       [0.8819052 ],
       [0.8055707 ],
       [0.23831691],
       [0.16979495],
       [0.7242665 ],
       [0.62726367],
       [0.22843266],
       [0.7928223 ],
       [0.378172  ],
       [0.18227994],
       [0.6894105 ],
       [0.603582  ],
       [0.6868917 ],
       [0.9136276 ],
       [0.5722292 ],
       [0.69358844],
       [0.70226985],
       [0.49999753],
       [0.8770596 ],
       [0.14019887],
       [0.7615233 ],
       [0.12940452],
       [0.19974338],
       [0.16557176],
       [0.8298824 ],
       [0.46506506],
       [0.53045154],
       [0.18850736],
       [0.27850083],
       [0.15212351],
       [0.07199226],
       [0.48945352],
       [0.7521103 ],
       [0.19906749],
       [0.37552083],
       [0.85885066],
       [0.76248133],
       [0.80942774],
       [0.7414137 ],
       [0.7880618 ],
       [0.10352743],
       [0.351884  ],
       [0.690

In [ ]:
y_pred=np.where(y_pred > 0.5,1,0)
y_pred=y_pred.astype(int)
np.column_stack((y_pred,y_test))

array([[1, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0,

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[38 15]
 [ 6 46]]
0.8


In [ ]:
from tensorflow.keras.layers import Dropout
model=Sequential()
model.add(Dense(32,activation='relu',input_dim=49))
model.add(Dropout(0.2))
model.add(Dense(32,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,batch_size=32,epochs=15)

Epoch 1/15


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5328 - loss: 0.6957
Epoch 2/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5984 - loss: 0.6643 
Epoch 3/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5943 - loss: 0.6585 
Epoch 4/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6066 - loss: 0.6585 
Epoch 5/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6926 - loss: 0.6262 
Epoch 6/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6557 - loss: 0.6267 
Epoch 7/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6885 - loss: 0.6141 
Epoch 8/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7008 - loss: 0.6033  
Epoch 9/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7336 - loss: 0.5862 
Epoch 10/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7295 - loss: 0.5718 
Epoch 11/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7172 - loss: 0.5632 
Epoch 12/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7664 - loss: 0.5388 
Epoch 13/15


In [ ]:
y_pred=model.predict(x_test)
y_pred=np.where(y_pred > 0.5,1,0)
y_pred=y_pred.astype(int)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[39 14]
 [ 5 47]]
0.819047619047619


In [ ]:
from keras.callbacks import EarlyStopping
model=Sequential()
model.add(Dense(32,activation='relu',input_dim=49))
model.add(Dropout(0.2))
model.add(Dense(32,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
early_stop=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)
history=model.fit(x_train,y_train,batch_size=32,epochs=100,validation_split=0.2,callbacks=[early_stop],verbose=1)
y_pred=model.predict(x_test)
y_pred=np.where(y_pred > 0.5,1,0)
y_pred=y_pred.astype(int)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 4s 67ms/step - accuracy: 0.5538 - loss: 0.6924 - val_accuracy: 0.6327 - val_loss: 0.6671
Epoch 2/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5897 - loss: 0.6609 - val_accuracy: 0.6735 - val_loss: 0.6559
Epoch 3/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6564 - loss: 0.6441 - val_accuracy: 0.7143 - val_loss: 0.6464
Epoch 4/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6359 - loss: 0.6385 - val_accuracy: 0.6327 - val_loss: 0.6453
Epoch 5/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6564 - loss: 0.6236 - val_accuracy: 0.7143 - val_loss: 0.6350
Epoch 6/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6513 - loss: 0.6211 - val_accuracy: 0.7143 - val_loss: 0.6229
Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6769 - loss: 0.6139 - val_accuracy: 0.7143 - val_loss: 0.6076
Epoch 8/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6923 - loss: 0.5810 - val_accuracy: 0.7143 - val_loss:

1/4 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
[[37 16]
 [ 4 48]]
0.8095238095238095


In [24]:
from tensorflow.keras import layers, models, regularizers

model = Sequential()

model.add(Dense(32, activation='relu', kernel_regularizer=regularizers.L1(0.001), input_dim=49))
model.add(Dense(32, kernel_regularizer=regularizers.L1(0.001), activation='relu'))

#Output layer
model.add(Dense(1, activation='sigmoid'))


model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train,batch_size=32, epochs=15)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - accuracy: 0.5820 - loss: 1.0510
Epoch 2/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7254 - loss: 1.0141
Epoch 3/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7500 - loss: 0.9855
Epoch 4/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7664 - loss: 0.9606 
Epoch 5/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7746 - loss: 0.9353
Epoch 6/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7705 - loss: 0.9101
Epoch 7/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7541 - loss: 0.8863
Epoch 8/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7746 - loss: 0.8594
Epoch 9/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7623 - loss: 0.8363 
Epoch 10/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7623 - loss: 0.8122
Epoch 11/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7746 - loss: 0.7890
Epoch 12/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7787 - loss: 0.7701

In [26]:
y_pred=model.predict(x_test)
y_pred = np.where(y_pred > 0.5, 1, 0)
y_pred = y_pred.astype(int)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 96ms/step
[[42 11]
 [ 7 45]]
0.8285714285714286


In [28]:
from tensorflow.keras import layers, models, regularizers

model = Sequential()
model.add(Dense(32, activation='relu', kernel_regularizer=regularizers.L2(0.001), input_dim=49))
model.add(Dense(32, kernel_regularizer=regularizers.L2(0.001), activation='relu'))

#Output layer
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train,batch_size=32, epochs=15)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.5246 - loss: 0.7659
Epoch 2/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6311 - loss: 0.7318 
Epoch 3/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6475 - loss: 0.7151 
Epoch 4/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7049 - loss: 0.6932
Epoch 5/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7336 - loss: 0.6715 
Epoch 6/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7664 - loss: 0.6530 
Epoch 7/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7459 - loss: 0.6362 
Epoch 8/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7705 - loss: 0.6162 
Epoch 9/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7828 - loss: 0.5992 
Epoch 10/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7787 - loss: 0.5826 
Epoch 11/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7787 - loss: 0.5676 
Epoch 12/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7787 - loss: 0.5513 
Ep

In [30]:
y_pred=model.predict(x_test)
y_pred = np.where(y_pred > 0.5, 1, 0)
y_pred = y_pred.astype(int)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[38 15]
 [ 6 46]]
0.8


In [33]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,BatchNormalization,Dropout
model=Sequential()
model.add(Dense(32, activation='relu', input_dim=49))
model.add(BatchNormalization())          # Normalize activations to stabilize learning
model.add(Dropout(0.3))
model.add(Dense(32, activation='relu', input_dim=49))
model.add(BatchNormalization())          # Normalize activations to stabilize learning
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train,batch_size=32, epochs=15)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.4877 - loss: 1.0369
Epoch 2/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6230 - loss: 0.7163 
Epoch 3/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6680 - loss: 0.6700 
Epoch 4/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6516 - loss: 0.7045 
Epoch 5/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7131 - loss: 0.5772 
Epoch 6/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7172 - loss: 0.5816 
Epoch 7/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7090 - loss: 0.5694 
Epoch 8/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7746 - loss: 0.4822 
Epoch 9/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7418 - loss: 0.5092 
Epoch 10/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7090 - loss: 0.5424 
Epoch 11/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7623 - loss: 0.4915 
Epoch 12/15
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7787 - loss: 0.4752 
Ep

In [34]:
y_pred=model.predict(x_test)
y_pred = np.where(y_pred > 0.5, 1, 0)
y_pred = y_pred.astype(int)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
[[30 23]
 [ 2 50]]
0.7619047619047619
